"""Remove storage_path

Revision ID: d625898e56c1
Revises: d447de1f8840
Create Date: 2026-07-04 08:16:44.951797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd625898e56c1'
down_revision = 'd447de1f8840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('storage_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_path', sa.VARCHAR(length=500), nullable=False))

    # ### end Alembic commands ###
